kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: gradle:jdk11
  commands:
  - cd backend/
  - ./gradlew assemble
  - ./gradlew check

- name: docker
  image: plugins/docker
  settings:
    username: 
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: mavarazo/archivit-backend
    dockerfile: backend/Dockerfile
