language: java

jdk:
  - openjdk11

jobs:
  include:
    - stage: build
      script:
        - cd backend
        - ./gradlew build
    - stage: test
      script: 
        - cd backend
        - ./gradlew check
    - stage: build image
      script:
        - cd backend
        - ./gradlew bootBuildImage
    - stage: deploy
      script: 
        - cd backend
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push mavarazo/archivit-backend