language: java

jdk:
  - openjdk11
  
script:
  - cd backend
  - ./gradlew build
  - ./gradlew check
  - ./gradlew bootBuildImage
  - docker tag docker.io/library/archivit $DOCKER_USERNAME/archivit-backend

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push $DOCKER_USERNAME/archivit-backend