language: java

jdk:
  - openjdk11
script:
  - cd backend
  - ./gradlew build
  - ./gradlew check
  - ./gradlew bootBuildImage

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push mavarazo/archivit-backend