language: java

jdk:
  - openjdk11
  
script:
  - cd backend
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew bootBuildImage --imageName=$DOCKER_USERNAME/archivit-backend

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push $DOCKER_USERNAME/archivit-backend